project_id = "bzxmejzssxjazswgwqqs"

[functions.check-program-expiration]
verify_jwt = false

[functions.frame]
verify_jwt = false

[functions.framesnap-frame]
verify_jwt = false

[functions.upload-to-ipfs]
verify_jwt = false

[functions.check-token-ownership]
verify_jwt = false
