/**
 * Concierge documentation search (BM25 over sections built from site docs).
 * Data: concierge-knowledge-data.ts (generated by scripts/build-concierge-knowledge.mjs).
 */
import { KNOWLEDGE, type KnowledgeSection } from "./concierge-knowledge-data.ts";

const STOP = new Set(
  "the a an and or of to in on for is are be how do i my me what where why can with it this that you your from at by as not no yes как что где мне мой мои у я и в на с по для это ли не а то".split(" "),
);

// Light RU→EN bridging so Russian questions hit English docs.
const RU_EN: Record<string, string[]> = {
  балл: ["points", "earn", "mint"], баллы: ["points"], получ: ["earn", "receive"], заработ: ["earn"],
  начисл: ["mint", "earn"], откуда: ["earn", "come"], ваучер: ["voucher", "redeem"], наград: ["reward"],
  программ: ["program"], создать: ["create"], создай: ["create"], минт: ["mint"], выпуст: ["mint", "issue"],
  кошел: ["wallet"], сертификат: ["certificate", "gift"], подарочн: ["gift", "certificate"],
  обмен: ["p2p", "exchange", "escrow"], перевод: ["transfer"], отправ: ["transfer", "send"],
  тариф: ["plan", "pricing"], цена: ["pricing", "price"], стоим: ["pricing", "price"], подписк: ["subscription", "billing"],
  агент: ["agent", "api", "mcp"], ключ: ["key", "api"], команд: ["team", "employee"], сотрудник: ["employee", "team"],
  касс: ["cashier"], филиал: ["branch"], клиент: ["customer"], уровн: ["tier"], реферал: ["referral"],
  истек: ["expired", "expiration"], продл: ["extend"], актив: ["active", "activate"], погас: ["redeem", "used"],
  qr: ["qr"], газ: ["gas"], комисс: ["fee"], вход: ["sign", "login"], войти: ["sign", "login"],
};

function tokens(text: string): string[] {
  const raw = text.toLowerCase().match(/[a-zа-яё0-9_]{2,}/g) ?? [];
  const out: string[] = [];
  for (const t of raw) {
    if (STOP.has(t)) continue;
    out.push(t.length > 5 ? t.slice(0, 6) : t);
    for (const [ru, en] of Object.entries(RU_EN)) if (t.startsWith(ru)) out.push(...en.map((e) => e.slice(0, 6)));
  }
  return out;
}

type Indexed = { s: KnowledgeSection; tf: Map<string, number>; len: number };
let index: { docs: Indexed[]; df: Map<string, number>; avg: number } | null = null;

function build() {
  const docs: Indexed[] = KNOWLEDGE.map((s) => {
    const tf = new Map<string, number>();
    const toks = tokens(`${s.title} ${s.title} ${s.text}`);
    for (const t of toks) tf.set(t, (tf.get(t) ?? 0) + 1);
    return { s, tf, len: toks.length };
  });
  const df = new Map<string, number>();
  for (const d of docs) for (const t of d.tf.keys()) df.set(t, (df.get(t) ?? 0) + 1);
  const avg = docs.reduce((a, d) => a + d.len, 0) / Math.max(1, docs.length);
  index = { docs, df, avg };
  return index;
}

export function searchDocs(query: string, k = 3): KnowledgeSection[] {
  const idx = index ?? build();
  const q = [...new Set(tokens(query))];
  if (!q.length) return [];
  const N = idx.docs.length;
  const scored = idx.docs.map((d) => {
    let score = 0;
    for (const t of q) {
      const f = d.tf.get(t);
      if (!f) continue;
      const n = idx.df.get(t) ?? 0;
      const idf = Math.log(1 + (N - n + 0.5) / (n + 0.5));
      score += idf * (f * 2.2) / (f + 1.2 * (0.25 + 0.75 * d.len / idx.avg));
    }
    if (d.s.source === "portal-map") score *= 1.4;
    return { d, score };
  }).filter((x) => x.score > 0).sort((a, b) => b.score - a.score);
  return scored.slice(0, k).map((x) => x.d.s);
}

export function formatDocs(hits: KnowledgeSection[], maxChars = 4500): string {
  if (!hits.length) return "No matching Loyal Spark documentation.";
  let out = "";
  for (const h of hits) {
    const block = `### ${h.title} [${h.source}]\n${h.text}\n\n`;
    if (out.length + block.length > maxChars) break;
    out += block;
  }
  return out.trim() || hits[0].text.slice(0, maxChars);
}
