/** MCP tool ids exposed by `supabase/functions/loyalty-mcp/index.ts` — keep in sync with server. */
export const MCP_TOOL_NAMES = [
  "get_platform_info",
  "get_my_profile",
  "list_loyalty_programs",
  "create_loyalty_program",
  "register_loyalty_program",
  "activate_loyalty_program",
  "update_program_status",
  "list_rewards",
  "create_reward",
  "mint_loyalty_tokens",
  "transfer_loyalty_tokens",
  "earn_points",
  "get_token_balance",
  "get_program_analytics",
  "list_marketplace_offers",
  "redeem_reward",
  "use_voucher",
  "check_voucher_status",
  "get_platform_stats",
  "cancel_stale_offers",
  "create_personalized_offer",
  "update_reward_status",
  "export_customers",
  "send_report",
  "list_my_reports",
  "update_report_status",
  "delete_report",
] as const;

export const MCP_TOOL_COUNT = MCP_TOOL_NAMES.length;
